# Generated by Django 4.2 on 2023-04-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Name of title')),
                ('no', models.CharField(max_length=4, verbose_name='No')),
                ('item', models.TextField(verbose_name='Item')),
                ('responsible', models.CharField(max_length=50, verbose_name='Responsible')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('status', models.TextField(verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Other notes')),
            ],
            options={
                'verbose_name': 'Protocol data',
                'verbose_name_plural': 'Protocol data',
            },
        ),
    ]
